### ISSUE TITLE
[BUG] Not working: Bar1 and Bar2 Overwrite

### ISSUE THREAD

**Issue by kiloforce** [Moerill/token-mold#146] opened 2022-10-13 05:44 UTC
**Describe the bug**
The Bar 1 and Bar 2 are not being overwritten on new token drop, nor on "reapplies"

**To Reproduce**
1. Set token's Bar 1 Attribute or Bar 2 Attribute
2. Set the "Modify Default Config" -> "Overwrite" for "Bar 1" or "Bar 2"
3. Click the "Reapply" Token Mold button
4. See that token not updated

**Expected behavior**
Should update "Bar 1" and "Bar 2" attributes

**Module incompatibilities**
Only module activated for above test is Token Mold.

**Screenshots/GIFs/Videos**
Example Overwrite Setting:
![image](https://user-images.githubusercontent.com/433058/195511266-4577efa9-ca0d-4c54-8847-9880d80ae000.png)

Example Token Not Updated:
![image](https://user-images.githubusercontent.com/433058/195511224-51a6aedc-3a9b-4e11-a556-2eaa4f050dce.png)

**Desktop (please complete the following information):**
 - OS: Windows OS
 - Browser: Chrome
 - FVTT Version: 10 v288 (tried on v287 before updating and trying again)
 - Module version: 2.15.4

**Comment by rockwallguy** [comment] 2022-11-20 03:13
I can confirm that this is a current bug.  I came here to post the same thing.  I've asked others to test it as well and they are experiencing the same thing.  Definitely not working as intended.  The bars just aren't updating on drop or on update.

**Comment by BeardedGnome** [comment] 2024-09-27 01:57
I'm closing all issues from version early than v2.22.2. Please update to Foundry V12, retest, and open a new issue if you're still having problems.

**Closed by BeardedGnome** 2024-09-27 01:57 UTC
Labels: bug
