### ISSUE TITLE
[BUG] Token Mold is not able to be installed

### ISSUE THREAD

**Issue by Elsabio83** [Moerill/token-mold#168] opened 2023-06-20 19:14 UTC
**Describe the bug**
I try to install the Module in the newest stable V11 FVTT and i get the following message:

Error: Unable to load valid module manifest data from "https://raw.githubusercontent.com/Moerill/token-mold/v2.15.1/module.json"
Module validation errors:
  packs: 
    0: 
      type: may not be undefined
    at Module.installPackage (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/packages/views.mjs:1:1634)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SetupView.handlePost (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/server/views/setup.mjs:1:2076)
fetch @ foundry.js:67697

**To Reproduce**
1. Go to Add-on modules in the FVTT intro page
2.  Click on Install module
3. Search for token Mold
4. Click on Install
5. See error described above

**Expected behavior**
Expected to install the Module

**Module incompatibilities**
I am jsut rying to install it, so i dont think Module imcompatibilities could be an issue, But if you say so i can start uninstalling

**Screenshots/GIFs/Videos**
> A picture is worth a thousand words.
![image](https://github.com/Moerill/token-mold/assets/135893022/19d6df1a-8156-4404-8e8d-ec662de50bbf)

**Desktop (please complete the following information):**
 - OS: [Windows 10 Pro/22H2]
 - Browser [Chrome]
 - FVTT Version [V11 Build 302]
 - Module version [2.15.1]

**Additional context**

**Comment by rictic** [comment] 2023-06-30 23:36
I'm seeing this as well

**Comment by Geekswordsman** [comment] 2023-07-05 13:16
v2.15.4 is not compatible with v11, thus can't be installed.  v2.5.0 is being worked on as an intermediate release to correct this :)

Duplicate of #167

**Closed by Geekswordsman** 2023-07-05 13:16 UTC
Labels: bug
