### ISSUE TITLE
Overlay not showing

### ISSUE THREAD

**Issue by Khybersghost** [Moerill/token-mold#11] opened 2020-05-23 22:07 UTC
Currently whenever I first load into Foundry or anytime I refresh / reload (F5), the overlays on the tokens won't show. I can't explain why, but if I simply change over to another scene it will start showing correctly, including if I change back to the original scene in question. I disabled all other mods with the exception of Token Mold and I can reproduce it 100% reliably. 

Windows 10
Foundry 0.6.0
Token Mold Ver 2.6.1
Pathfinder 2nd Edition ruleset

**Comment by Moerill** [comment] 2020-05-23 22:32
interesting
can't reproduce it at all
what are the exact settings you've set up for the overlay?
and which browser are you  using?
does the regular hover from FVTT show? (the rectangle)?

**Comment by Khybersghost** [comment] 2020-05-23 22:46
It's from the Foundry program, not the browser. When I hover over the tokens the regular box appears. 
Showing AC, HP, Speed and Perception on overlay. Applying other settings to unlinked tokens (numeric suffix)

**Comment by Khybersghost** [comment] 2020-05-23 22:47
I first noticed it in Foundry ver 0.5.6 but hadn't gotten around to posting about it

**Comment by Moerill** [comment] 2020-05-23 23:02
could you test one thing please:
try to reproduce it, go into console.
- First check for errors. (if there are some, post them here please)
- then type ```Hooks.on('hoverToken', (...args) => console.log('Hover', args));``` hover over a few tokens, observe the output and paste a screenshot here, please

**Comment by Khybersghost** [comment] 2020-05-23 23:34
No errors at baseline.
After pasting Hooks.on('hoverToken', (...args) => console.log('Hover', args)); I get 
![TokenMold](https://user-images.githubusercontent.com/65833146/82742451-35c0f900-9d13-11ea-8aa0-f8fa8d8fc4c9.png)

**Comment by Khybersghost** [comment] 2020-05-23 23:34
Hovering over several tokens

**Comment by MeJauk** [comment] 2020-05-25 18:18
For me the problem appears when tabbing out of the browser window, or just pressing alt and hovering over tokens (happens in FF and chrome).

**Comment by Moerill** [comment] 2020-05-26 08:10
> No errors at baseline.
> After pasting Hooks.on('hoverToken', (...args) => console.log('Hover', args)); I get
> ![TokenMold](https://user-images.githubusercontent.com/65833146/82742451-35c0f900-9d13-11ea-8aa0-f8fa8d8fc4c9.png)

And still no overlay appearing?
hmpf
unsure what causes this, need some digging around...

**Comment by Shandyan** [comment] 2020-05-27 09:08
I've just noticed the same bug. Oddly, when I log in as a player (via browser), they can see the overlay for the tokens they own - but I can't see any overlays at all as GM!

**Comment by Moerill** [comment] 2020-05-27 09:21
if i see it correctly this error persists already for longer than Token Mold v2.6?
Since i can't replicate it on my end, i need you people to help me find the bug! (propably)

i'm rather busy for this week, but could you contact me on discord (  Moerill#7205 ) so i could come back to you for some further testing, when i get around to take a deeper look here?

**Comment by Khybersghost** [comment] 2020-05-27 16:14
> For me the problem appears when tabbing out of the browser window, or just pressing alt and hovering over tokens (happens in FF and chrome).
> 
> @Khybersghost
> Are you using EasyTarget? Deactivating that fixed it (for now at least).
> 
> Edit #2:
> Holding Alt and hovering over tokens broke it again, but at least now I can reset it with a refresh.

Not using easy target. I do have a good number of mods but the issue persisted with all other mods disabled. My issue sounds identical to Shandyan. I'll keep looking to see if I catch any errors in the F12 console or notice any other curious interaction.

**Comment by MeJauk** [comment] 2020-06-01 12:33
Reinstalled the module after upgrading Foundry to 0.6.1. What I have to do to make the overlay appear is reloading the scene (switching to another and back).

Other than that, the overlay seems to be working flawless now (also no more bugging out when holding Alt and hovering over tokens).

**Comment by Moerill** [comment] 2020-06-04 08:43
I am going to try to redesign the overlay a bit for the next update and hopefully fix this issue here. (thus closing this issue. If it arises again next patch, please create a new issue or comment on this one and i'll reopen it)
If you have any ideas/wishes for the overlay rewrite, please post them here:
https://github.com/Moerill/token-mold/issues/18

**Closed by Moerill** 2020-06-04 08:43 UTC

**Comment by drplote** [comment] 2022-06-22 02:20
Just wanted to note that I'm setting this same behavior two years later.

As mentioned above, changing scenes fixes it.
