### ISSUE TITLE
[BUG] Token overlay not working (not displaying)

### ISSUE THREAD

**Issue by vortam** [Moerill/token-mold#29] opened 2020-07-09 19:41 UTC
Module version 2.6.1
System Pathfinder 1 ed 0.64
FVTT version 0.6.5

When placing tokens, no matter what settings, overlay is not showing.

Console shows no error, just "Foundry VTT | Created Token lLXksgVSvDFuGcHU in parent Scene 7itFIw2I169v53Na"
All other modules turned off
Settings example in console: 

Token Mold | Saving Settings ObjectunlinkedOnly: falsename: {use: true, number: {…}, remove: false, prefix: {…}, replace: "nothing", …}hp: {use: true, toChat: true}size: {use: true}config: {use: true, vision: {…}, displayBars: {…}, bar1: {…}, bar2: {…}, …}overlay: {use: true, attrs: Array(4)}__proto__: Object

At least one other person mentioned this at foundry discord recently
My Discord :  Will#6479

**Comment by Moerill** [comment] 2020-07-09 20:47
I do think its fixed now
at least i can't reproduce it anymore.

**Closed by Moerill** 2020-07-09 20:47 UTC
