### ISSUE TITLE
0.70 Settings - Tab content is not shown

### ISSUE THREAD

**Issue by Norc** [Moerill/token-mold#34] opened 2020-07-20 10:26 UTC
in 0.70 in a test world with all my modules disabled, including Tidy UI Settings, I get the following in the token mold config settings:

![image](https://user-images.githubusercontent.com/64667579/87927893-ec123780-ca51-11ea-9b03-a8226715e609.png)

All of the tabs are blank excpet the last one. Note that it looks like Luminous may still be applying settings even though it is off.

**Comment by Moerill** [comment] 2020-07-20 10:40
thanks for the report. i can reproduce it, even without luminous installed.

I actually do not know what is happening here and don't have the time until at least the weekend to work this out - buuut its for the alpha release, so its no hurry imo.

**Comment by Norc** [comment] 2020-07-20 13:19
Thanks. module seems to be working well otherwise! I'm thinking of reverting to 0.6.5 briefly to change my Token Mold settings which should work even.

Appreciate you looking into it, sir.

**Comment by Moerill** [comment] 2020-07-20 13:38
As a note to myself, or someone else wanting to take a look at this:
For *some* reason the tab system doesn't work. While t he tabs in the navigation get marked as active, the divs containing the content don't.
Taking a quick look at what i'm doing with tabs and comparing it e.g. to DrawingConfig, i do not see what i'm doing differently there.

**Comment by BrotherSharper** [comment] 2020-07-28 13:39
Seems to be related to a bugfix in 0.7.0
`Corrected an issue that would cause nested Tabs on the Actor sheet to disappear completely when the parent tab changed.`

You might want to discuss this with atropos

**Comment by BrotherSharper** [comment] 2020-07-29 03:24
I think I have found the solution,
`<div class='tab' data-tab='Info' data-group='configs'>` needs to have the data-group sent over to `    <nav class="sheet-tabs tabs">` in the token-mold.html

**Closed** 2020-08-30 23:20 UTC
Labels: bug
