### ISSUE TITLE
[FEATURE] Update for V12 Stable Update

### ISSUE THREAD

**Issue by wonsnot** [Moerill/token-mold#204] opened 2024-06-14 01:35 UTC
**Is your feature request related to a problem? Please describe.**
Foundry has updated to V12 stable and this module is listed as incompatible. 

**Describe the solution you'd like**
Update and test on Foundry V12

**Comment by GomatiGit** [comment] 2024-06-14 15:25
I updated to version 12 too and need and update on this module

**Comment by Deladriendil** [comment] 2024-06-15 00:49
+1

**Comment by Someone2345** [comment] 2024-06-17 14:02
everytime you forget how useful a module is, until you update and find that it is incompatible and you suddenly miss the features you took for granted.  +1 for v12 update please!  (automatic HP rolling and adjactive on mobs is/was a stable for our games, it is a tough life without this!)

**Comment by ThiefMaster** [comment] 2024-06-17 14:04
That's why you ideally don't upgrade you (production) foundry until your favorite modules are updated ;)

**Comment by kajishun** [comment] 2024-06-18 03:03
+1

**Comment by BeardedGnome** [comment] 2024-06-21 01:46
I'll try to address v12 in my fork once I have a v12 server running.

**Comment by BeardedGnome** [comment] 2024-06-23 05:52
V12 update - Fixed many of the warnings, but Foundry changed how dice are rolled and broke rolled health. Still investigating.

**Comment by BenNelsonNeb** [comment] 2024-06-30 15:20
Love token mold, Hoping to get it working in v12 as well. Another vote!

**Comment by BeardedGnome** [comment] 2024-07-03 21:32
I've rewritten the HP generation and will attempt to have something published (unofficial fork) by the end of the month.

**Comment by BeardedGnome** [comment] 2024-07-08 05:41
I've published an unofficial fork that should fix the issue, please test the version that matches your Foundry install.

Foundry v11:  `https://raw.githubusercontent.com/BeardedGnome/token-mold/v2.21.0/module.json`
Foundry v12:  `https://raw.githubusercontent.com/BeardedGnome/token-mold/v2.22.1/module.json`

**Comment by tobjv** [comment] 2024-07-23 19:15
> I've published an unofficial fork that should fix the issue, please test the version that matches your Foundry install.
> 
> Foundry v11: `https://raw.githubusercontent.com/BeardedGnome/token-mold/v2.21.0/module.json` Foundry v12: `https://raw.githubusercontent.com/BeardedGnome/token-mold/v2.22.1/module.json`

how does one use this exactly, I'm new to all this.

**Comment by wonsnot** [comment] 2024-07-23 23:16
> > I've published an unofficial fork that should fix the issue, please test the version that matches your Foundry install.
> > Foundry v11: `https://raw.githubusercontent.com/BeardedGnome/token-mold/v2.21.0/module.json` Foundry v12: `https://raw.githubusercontent.com/BeardedGnome/token-mold/v2.22.1/module.json`
> 
> how does one use this exactly, I'm new to all this.

This article explains how to install a new module by manifest URL. https://foundryvtt.com/article/modules/

**Comment by wonsnot** [comment] 2024-07-23 23:17
> I've published an unofficial fork that should fix the issue, please test the version that matches your Foundry install.
> 
> Foundry v11: `https://raw.githubusercontent.com/BeardedGnome/token-mold/v2.21.0/module.json` Foundry v12: `https://raw.githubusercontent.com/BeardedGnome/token-mold/v2.22.1/module.json`

Thanks! It seems to be working for me. I'll raise an issue over there if I run into any.

**Comment by tobjv** [comment] 2024-07-24 13:49
works for me so far as well

**Comment by kiloforce** [comment] 2024-08-05 06:48
> Foundry v12: `https://raw.githubusercontent.com/BeardedGnome/token-mold/v2.22.1/module.json`

This loaded and worked for me.  Thanks.

**Comment by ThiefMaster** [comment] 2024-08-05 19:58
With the v12 fork I get this error in a pf2e world when trying to open the Token Mold config dialog:

```
Error: An error occurred while rendering TokenMoldForm 27. PF2e System | Actor type base does not exist and actor module sub-types are not supported
    onError .../scripts/foundry.js:654
    render .../scripts/foundry.js:5794
    promise callback*render .../scripts/foundry.js:5792
    _renderActorDirectoryMenu .../modules/token-mold/scripts/token-mold.js:297
    _renderActorDirectoryMenu .../modules/token-mold/scripts/token-mold.js:291
    _hookActorDirectory .../modules/token-mold/scripts/token-mold.js:243
    initHooks .../modules/token-mold/scripts/token-mold.js:57
    #call .../scripts/foundry.js:632
    callAll .../scripts/foundry.js:589
    _callHooks .../scripts/foundry.js:5917
    _render .../scripts/foundry.js:5878
    _render .../scripts/foundry.js:72744
    _render .../scripts/foundry.js:73089
    _render .../scripts/foundry.js:73886
    render .../scripts/foundry.js:5792
    listen .../systems/pf2e/pf2e.mjs:1683
    #call .../scripts/foundry.js:632
    callAll .../scripts/foundry.js:589
    setupGame .../scripts/foundry.js:9097
    _initializeGameView .../scripts/foundry.js:10431
    _initializeView .../scripts/foundry.js:10407
    initialize .../scripts/foundry.js:8994
    async* .../scripts/foundry.js:95938
    async* .../scripts/foundry.js:95918
Caused by: Error: PF2e System | Actor type base does not exist and actor module sub-types are not supported
    ErrorPF2e .../systems/pf2e/pf2e.mjs:1
    construct .../systems/pf2e/pf2e.mjs:1608
    get _actorAttributes/shellMap< .../modules/token-mold/scripts/token-mold.js:1388
    get _actorAttributes .../modules/token-mold/scripts/token-mold.js:1388
    getData .../modules/token-mold/scripts/token-mold.js:1179
    _render .../scripts/foundry.js:5837
    _render .../scripts/foundry.js:6571
    render .../scripts/foundry.js:5792
    _renderActorDirectoryMenu .../modules/token-mold/scripts/token-mold.js:297
    _renderActorDirectoryMenu .../modules/token-mold/scripts/token-mold.js:291
    _hookActorDirectory .../modules/token-mold/scripts/token-mold.js:243
    initHooks .../modules/token-mold/scripts/token-mold.js:57
    #call .../scripts/foundry.js:632
    callAll .../scripts/foundry.js:589
    _callHooks .../scripts/foundry.js:5917
    _render .../scripts/foundry.js:5878
    _render .../scripts/foundry.js:72744
    _render .../scripts/foundry.js:73089
    _render .../scripts/foundry.js:73886
    render .../scripts/foundry.js:5792
    listen .../systems/pf2e/pf2e.mjs:1683
    #call .../scripts/foundry.js:632
    callAll .../scripts/foundry.js:589
    setupGame .../scripts/foundry.js:9097
    _initializeGameView .../scripts/foundry.js:10431
    _initializeView .../scripts/foundry.js:10407
    initialize .../scripts/foundry.js:8994
    async* .../scripts/foundry.js:95938
    async* .../scripts/foundry.js:95918
foundry.js:655:30
    onError .../scripts/foundry.js:655
    render .../scripts/foundry.js:5794
    (Async: promise callback)
    render .../scripts/foundry.js:5792
    _renderActorDirectoryMenu .../modules/token-mold/scripts/token-mold.js:297
    (Async: EventListener.handleEvent)
    _renderActorDirectoryMenu .../modules/token-mold/scripts/token-mold.js:291
    _hookActorDirectory .../modules/token-mold/scripts/token-mold.js:243
    initHooks .../modules/token-mold/scripts/token-mold.js:57
    #call .../scripts/foundry.js:632
    callAll .../scripts/foundry.js:589
    _callHooks .../scripts/foundry.js:5917
    _render .../scripts/foundry.js:5878
    _render .../scripts/foundry.js:72744
    _render .../scripts/foundry.js:73089
    _render .../scripts/foundry.js:73886
    render .../scripts/foundry.js:5792
    listen .../systems/pf2e/pf2e.mjs:1683
    #call .../scripts/foundry.js:632
    callAll .../scripts/foundry.js:589
    setupGame .../scripts/foundry.js:9097
    _initializeGameView .../scripts/foundry.js:10431
    _initializeView .../scripts/foundry.js:10407
    initialize .../scripts/foundry.js:8994
    <anonymous> .../scripts/foundry.js:95938
    <anonymous> .../scripts/foundry.js:95918
```

**Comment by ThiefMaster** [comment] 2024-08-05 20:30
```js
const types = Actor.implementation.TYPES.filter(x => x !== 'base');
```

Seems to be a good workaround for this error. Not sure if this breaks any functionality for the stat overlay, but when not using it it's certainly better than not being able to configure the module at all.

**Comment by DanBonser** [comment] 2024-08-05 23:14
> Foundry v12: `https://raw.githubusercontent.com/BeardedGnome/token-mold/v2.22.1/module.json`

This 90% works for me.  When I bring in new tokens that don't have vision already on them, its not overriding their vision to be on, although I have it selected.  I'm having to go back and indivitually check every token to make sure vision is on.  Beyond that, its working well.

**Comment by mattimeo84** [comment] 2024-08-06 00:50
Added it and it works great. however, now i have no roll table of adjectives. is there a way to just load those?

**Comment by BeardedGnome** [comment] 2024-08-06 05:19
> ```js
> const types = Actor.implementation.TYPES.filter(x => x !== 'base');
> ```
> 
> Seems to be a good workaround for this error. Not sure if this breaks any functionality for the stat overlay, but when not using it it's certainly better than not being able to configure the module at all and at least during a quick test it seemed to offer all relevant attributes.

You are correct. I need to filter out the 'base' type in a couple places in the code.

**Comment by BeardedGnome** [comment] 2024-08-06 05:20
> > Foundry v12: `https://raw.githubusercontent.com/BeardedGnome/token-mold/v2.22.1/module.json`
> 
> This 90% works for me. When I bring in new tokens that don't have vision already on them, its not overriding their vision to be on, although I have it selected. I'm having to go back and indivitually check every token to make sure vision is on. Beyond that, its working well.

I have no idea how vision works. I'll see if I can reproduce the issue. No ETA at this time.

**Comment by Mrfikser** [comment] 2024-08-08 19:38
> I've published an unofficial fork that should fix the issue, please test the version that matches your Foundry install.
> 
> Foundry v11: `https://raw.githubusercontent.com/BeardedGnome/token-mold/v2.21.0/module.json` Foundry v12: `https://raw.githubusercontent.com/BeardedGnome/token-mold/v2.22.1/module.json`

I really appreciate you doing this and it's made the module function for me. The one hangup that I've run into is that I can not get the settings to show up when I hit the gear icon in the actors tab. Could be a me problem, though.

**Comment by ThiefMaster** [comment] 2024-08-08 19:40
No, it's a bug that's not been fixed yet. See my previous comment in here for a workaround (you can edit the installed module for this until there's a fixed release).

**Comment by Mrfikser** [comment] 2024-08-08 19:53
I'm the type that will wait for a fix. Thanks.

**Comment by BeardedGnome** [comment] 2024-08-09 08:21
@ThiefMaster - Try this release.

V12: https://raw.githubusercontent.com/BeardedGnome/token-mold/v2.22.2/module.json

**Comment by ThiefMaster** [comment] 2024-08-09 13:57
Thanks, works fine AFAICT.

**Comment by Mrfikser** [comment] 2024-08-26 20:04
> @ThiefMaster - Try this release.
> 
> V12: https://raw.githubusercontent.com/BeardedGnome/token-mold/v2.22.2/module.json

I don't suppose there's a way to make this the official version in Foundry is there? I'm not asking you to take anything from the original author. It looks like it has been over a year since they've pushed an update out and it would be nice for those of us less inclined technical if something like that happened.

**Comment by BeardedGnome** [comment] 2024-08-26 21:57
> > @ThiefMaster - Try this release.
> > V12: https://raw.githubusercontent.com/BeardedGnome/token-mold/v2.22.2/module.json
> 
> I don't suppose there's a way to make this the official version in Foundry is there? I'm not asking you to take anything from the original author. It looks like it has been over a year since they've pushed an update out and it would be nice for those of us less inclined technical if something like that happened.

I don't have any way of doing that. If one of the maintainers wants to review my pull requests, we can get master updated.

**Comment by Mrfikser** [comment] 2024-08-26 22:40
> > > @ThiefMaster - Try this release.
> > > V12: https://raw.githubusercontent.com/BeardedGnome/token-mold/v2.22.2/module.json
> > 
> > 
> > I don't suppose there's a way to make this the official version in Foundry is there? I'm not asking you to take anything from the original author. It looks like it has been over a year since they've pushed an update out and it would be nice for those of us less inclined technical if something like that happened.
> 
> I don't have any way of doing that. If one of the maintainers wants to review my pull requests, we can get master updated.

I hope there's a way to make this happen. I'm using what you've given us, but it bugs me that it can't be updated elsewhere. Thanks for making this amazing mod continue working as Foundry updates.

**Comment by kiloforce** [comment] 2024-08-27 03:59
> I don't suppose there's a way to make this the official version in Foundry is there? I'm not asking you to take anything from the original author. It looks like it has been over a year since they've pushed an update out and it would be nice for those of us less inclined technical if something like that happened.

Fortunately, it was listed under the MIT license (https://github.com/Moerill/token-mold/blob/master/LICENSE).

An abandoned project is left with really two options:

1) One could fork the project, create a new divergent project, and submit the divergent project to be listed on Foundry.  This would be a good option if significant improvements were planned.

2) Alternatively, if only minor changes are needed, one could fork the project and make a case to the Foundry Project
 to update the listing and point to a new source link.


Foundry contact information can be found on the Module Packaging Guide: https://foundryvtt.com/article/packaging-guide/

**Comment by Symon-S** [comment] 2024-09-01 19:55
@BeardedGnome Maybe you can ask Moerill to take over the project?

**Comment by r-valyar** [comment] 2024-09-18 08:49
@BeardedGnome have you managed to talk with Moerill or decided to take over as alternative Fork?

**Comment by Moerill** [comment] 2024-09-18 13:15
Heya,
Should i add you as a maintainer @BeardedGnome ?
I'm still of the whole foundry train and have no real time to validate anything, so i'm not touching it :see_no_evil: 

Regarding the foundry package, @Geekswordsman currently has control over it afaik. (He also took care of this module for quite some time already after i left. So huge thanks to them! :heart_hands: But they seem to be taking (at least) a pause as well.

Alternatively, as already mentioned: The project is licensed under MIT, so whoever wants to, feel free to just take it and take matters in your own hands.

**Comment by BeardedGnome** [comment] 2024-09-20 05:33
Hey @Moerill , thank you for joining the conversation. @Geekswordsman has been AFK so I guess if you don't mind me contributing you can add me. My fork continues to diverge from the baseline, at this point to bring my master over would be more of a rewrite than a merge.

As long as you're OK with that, I'll do what I can. I'm a C\C++ developer by trade, so using Javascript is quite a trip.

**Comment by Moerill** [comment] 2024-09-20 09:32
Sent you an invite!
No worries about rewriting and so on. I wanted to completly rewrite the thing before i stopped anyway and i think there is also a branch of @Geekswordsman attempt of rewriting.
If you need control over the foundry package though, you need to contact foundry staff. 

This project kind of resembles my first steps in JavaScript (and properly building a project), so ... a lot to change and improve there :sweat_smile: 
Good luck ! And if you have some co-collaborators or so, feel free to leave me a message.. somewhere... i'll try to take a look from time to time :)

**Comment by BeardedGnome** [comment] 2024-09-20 20:03
Thank you @Moerill . I'm out of town the next few days, but in the next few weeks I'll see about getting the official release updated.

**Comment by Mrfikser** [comment] 2024-09-20 20:34
I'm very excited about this gang! Thanks to everyone making it happen.

**Comment by wonsnot** [comment] 2024-09-20 23:06
@BeardedGnome @Moerill Thank you both for all the hard work you are doing to make/keep this module alive. 

I think we can close this issue after the merge in favor of more targeted issues relevant to V12 support.

Once again thanks for all that you do.

**Comment by BeardedGnome** [comment] 2024-09-24 04:39
I published my V11 update, just to test out the flow. Looks like I still need access to the Foundry page. I'll fire off an email to them.

**Comment by BeardedGnome** [comment] 2024-09-27 01:05
Foundry 11 version V2.21.0 and Foundry 12 version v2.22.2 now showing up on the official page. I'm closing this issue.

Open a new one if you notice something amiss.

**Closed by BeardedGnome** 2024-09-27 01:05 UTC
