### ISSUE TITLE
[BUG] token mold is throwing an error in the console when token scaling option is turned on

### ISSUE THREAD

**Issue by Orionox** [Moerill/token-mold#122] opened 2022-03-19 16:40 UTC
when the "Set token size to creature size and scale to map scale" option is selected, an error is thrown in the console. 
![Capture](https://user-images.githubusercontent.com/20059838/159130033-0bf0fd16-8443-4b54-9f36-7eb434e1bd29.PNG)
Additionally, this setting appears to be messing with other modules. When turned off, this setting will also turn off the randomization that the module Token variant art uses. 

**Desktop:**
 - OS: Windows
 - FVTT Version 9
 - Module version Latest

**Comment by Geekswordsman** [comment] 2022-03-25 00:54
Not currently able to reproduce this using dnd5e v1.5.7; could you please supply more information?

What game system and version are you using?

Does this issue persist if Token Mold is the only module enabled?

**Comment by Orionox** [comment] 2022-03-25 01:19
> Not currently able to reproduce this using dnd5e v1.5.7; could you please supply more information?
> 
> What game system and version are you using?
> 
> Does this issue persist if Token Mold is the only module enabled?

I'm also on v1.5.7, Here's what "find the culprit" came up with
![Capture](https://user-images.githubusercontent.com/20059838/160036016-94e9397a-7431-4758-91f8-e217f6772d26.PNG)

**Comment by Geekswordsman** [comment] 2022-03-25 01:24
Can you please post the full Token Mold version, and additionally do the test I mentioned earlier with Token Mold being the only module enabled?

**Comment by Orionox** [comment] 2022-03-25 01:36
Token Mold 2.15.1
The error does persist when token mold is the only module activated.

**Comment by Geekswordsman** [comment] 2022-03-25 01:40
Interesting...  Thanks for checking that.  I'll try and reproduce further.  If you are aware of these other questions and can answer them, great - if not it's alright and I'll have to play around with settings to see where the issue might be.

Does this happen for any token, or only tokens of a specific size?

Any grid scale? Or only a grid scale above/below a certain amount?

**Comment by Orionox** [comment] 2022-03-25 02:03
I just tried it with a grid-scale of 50 instead of 100 and with a large monster. Got the same error

**Comment by Geekswordsman** [comment] 2022-03-25 02:09
I've already shut down for the evening, but this is a bit confusing as the last test I did was a grid scale 100, large creature, and no errors.

I would try uninstalling the module and reinstalling it fresh, then give a good cache clear (ctrl-f5) and make sure you have the latest version.

**Comment by Geekswordsman** [comment] 2022-04-14 20:59
Unable to reproduce and no further response; closing issue.  If reproduceable steps can be provided, will re-open.

**Closed by Geekswordsman** 2022-04-14 20:59 UTC
Labels: bug, unable to reproduce
