### ISSUE TITLE
[BUG] Modify Default Config - Token disposition - Overwrite

### ISSUE THREAD

**Issue by BronzeToad** [Moerill/token-mold#108] opened 2021-09-18 03:22 UTC
Foundry VTT v0.8.9
Token Mold v2.13.1

The Token Disposition: Overwrite radio button in Modify Default Config does not change on Save & Close. The dropdown does save, but the actual Overwrite check-box does not.

![Screen Shot 2021-09-17 at 10 19 22 PM](https://user-images.githubusercontent.com/45736019/133870895-2d559ddd-8b41-43a4-9cf1-3ef43572e514.png)
.

**Comment by Geekswordsman** [comment] 2021-12-06 02:17
Duplicate of #60

**Closed by Geekswordsman** 2021-12-06 02:17 UTC
Labels: bug
