### ISSUE TITLE
[BUG] 0.7.3 Menu not working

### ISSUE THREAD

**Issue by LorduFreeman** [Moerill/token-mold#63] opened 2020-09-30 22:09 UTC
Token Mold in 7.3 beta is creating tokens with randomized HP and custom names just fine but the menu to configure it does not display any info (so no configuration possible) and cannot be closed.

![image](https://user-images.githubusercontent.com/72170114/94744903-06ce2a00-037a-11eb-9576-500aa4a6376d.png)

Maybe a separate issue but Foundry displays a warning on dragging out a token as well relating to Token Mold:
foundry.js:9154 You are using the Die#rolls attribute which is deprecated in favor of Die#results.

**Comment by Moerill** [comment] 2020-10-01 08:15
I cannot reproduce this issue.
- Please test with all modules disabled, if you want help in compatibility testing i can suggest using the [find the culprit](https://github.com/Moerill/fvtt-find-the-culprit/) module. 
- Are there any console errors when opening the window?
- Also please provide browser and module version. That bug was an issue for an older token mold version.

**Comment by LorduFreeman** [comment] 2020-10-01 10:44
Chrome (85.0.4183.121), Nodejs 12.18.4, Foundry 0.7.3, DnD5e 0.96

This happens in a fresh world with all modules disabled.
No error messages. Interestingly, the Stat Overlay tab is displaying fine (and working without closing the window) while all others do not contain any text.

**Comment by apoapostolov** [comment] 2020-10-01 11:01
Maybe this is related to Settings Extender?

The mod Tokenizer has a similar issue with Settings, not being able to close the window and not able to save settings. It was fixed by ImagePicker.Image changed to ImagePicker.String. If similar issue is here, it could explain the behavior as I cannot close the window at all, only minimize it.

**Comment by Moerill** [comment] 2020-10-01 11:08
> Maybe this is related to Settings Extender?

would be strange since he/she/* stated that its in a fresh world with all other modules disabled.

@apoapostolov  did you encounter this bug as well in 0.7.3 with the newest token mold version?

i cannot reproduce it at all, neither with old nor new worlds and neither with chrome nor firefox.

**Comment by apoapostolov** [comment] 2020-10-01 11:12
Yes. 0.7.3, PF2 system, only Token Mold turned on (via Culprit). Save and Close doesn't click at all. I am in Electron Foundry.

![image](https://user-images.githubusercontent.com/4083812/94802310-16885580-03f0-11eb-894e-b2c3bb76d8ae.png)

**Comment by Moerill** [comment] 2020-10-01 11:19
and it did work with older FVTT versions?
i am sooo confused right now and don't know where to begin debugging..

Maybe its just finally time to do the planned token mold overhaul, including a cleaner settings menu....

**Comment by apoapostolov** [comment] 2020-10-01 11:24
Yes, it worked in 0.6.6

**Comment by apoapostolov** [comment] 2020-10-01 11:26
Yes, it worked perfectly before in 0.6.6.

**Comment by Moerill** [comment] 2020-10-01 11:45
hmm
i'll just use the 0.7.X beta time frame to do the token mold rework, using the fvtt beta as beta frame for "new" token mold as well.
(new in quotation marks, since i do not plan on adding features, mainly a code and settings overhaul. Hoping to improve on the base, with the experience i gained since i initially started this project years back. Token Mold really has been around for quite some time now..)

**Comment by Moerill** [comment] 2020-10-01 18:23
@apoapostolov could you please make sure that you're on the newest token mold version?
it seems like lordufreeman wasn't...

**Comment by Moerill** [comment] 2020-10-01 19:03
Issue seems to have been:
People on tokenmold pre 2.8 were stuck there, cause i failed to keep the old manifest which that version pointed to.
i added it and people should now be able to update...

**Comment by Moerill** [comment] 2020-10-02 11:21
Closing this for the time being.
If this did not solve the issue, please reopen this issue.

**Closed by Moerill** 2020-10-02 11:21 UTC
Labels: bug
