### ISSUE TITLE
Overlay not always displaying

### ISSUE THREAD

**Issue by JugglerBri** [Moerill/token-mold#51] opened 2020-09-08 03:36 UTC
**Describe the bug**
I've noticed a few times now that the overlay feature was not displaying any information at all. I even restarted my entire computer and it didn't help. I switched to a different world, switched back, and still, no overlay (even though the other world had an overlay). I then switched to a different scene in the problematic world and the overlay was working there, switched back, and the overlay was working.

**To Reproduce**
I'm not exactly what the steps are to reproduce the error. I've just noticed it happen a couple times now. If I can find some common theme when it happens, I'll make sure to update this (or comment or make a new post or whatever - I'm new to github).

**Expected behavior**
Pretty straight forward, the overlay should display as intended. Not much to add to this section, sorry.

**Module incompatibilities**
Next time it happens, I'll try to deactivate the other modules I'm running. The current list of modules I'm running are:

* Dice Tray
* Dice So Nice!
* Magic Items
* Shared Data (custom one I create based on THESE instructions)
* Token Mold
* VTTA DnD Beyond Integration
* VTTA Iconizer
* VTTA Tokenizer

**Screenshots/GIFs/Videos**
A picture wouldn't really add anything, the overlay just doesn't display

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome (but happens in the native client too)
 - FVTT Version 0.6.6
 - Module version 2.7.1

**Additional context**
Nothing to add but thanks for this, it was exactly what I was looking for!

**Comment by sandersontavares** [comment] 2020-09-08 06:13
I can confirm this bug, it has been happening to me too.

**Comment by Ironxxx** [comment] 2020-09-14 10:19
this happens to me constantly, normally at the start of a session. It can take up to 5 or 6 refreshes of Foundry to get the display to appear.

**Comment by Moerill** [comment] 2020-09-16 14:33
Hmm.. i thought i fixed this last big patch
i currently can't reproduce that beheviour at all, sadly and have no real clue why its happening. (Although i think i observed that on my game server as well, but can't reproduce it at all on my dev server. Maybe its because i'm currently on FVTT 0.7.2? :thinking: that would mean it would fix itself soon(tm) )

Please everyone do report back if you notice some behaviour that could be causing this!

**Comment by Moerill** [comment] 2020-10-25 10:11
Please take a look at https://github.com/Moerill/token-mold/issues/71 and leave your thoughts on the topic there, since this may resolve your issue.

**Comment by tbrockwood** [comment] 2022-02-02 21:13
Is there a fix for this issue? I'm on Foundry 8.9, and it's still randomly showing/not showing the overlay

**Comment by jbhaywood** [comment] 2022-05-12 06:17
I noticed that the Overlay option always turns itself off when you close the settings dialog. Maybe that's what's happening without people realizing it. The repro steps are:
- Turn Overlay option on
- Open settings dialog
- Close settings dialog
- Notice that the Overlay option is now turned off

**Closed** 2022-09-14 11:11 UTC
Labels: bug
